### ISSUE TITLE
Unable or not sure how to run with the jmeter webdriver sampler plugin

### ISSUE THREAD

**Issue by Aravindan21** [QAInsights/PerfAction#13]
Hi Naveen, hope you are doing good. We discussed this in your youtube channel. 

![image](https://user-images.githubusercontent.com/57444172/189994912-4c5e1982-69df-4402-80a2-495df150a6d6.png)

![image](https://user-images.githubusercontent.com/57444172/189994931-25af6cdb-e18e-4895-bbcb-d01d8fd4a559.png)

Issue is mainly with the line below:

<com.googlecode.jmeter.plugins.webdriver.config.ChromeDriverConfig guiclass="com.googlecode.jmeter.plugins.webdriver.config.gui.ChromeDriverConfigGui" testclass="com.googlecode.jmeter.plugins.webdriver.config.ChromeDriverConfig" testname="jp@gc - Chrome Driver Config" enabled="true">

I added this line in the file "jmeter-plugin-install.sh":
java -jar ${JMETER_HOME}/lib/cmdrunner-${JMETER_CMD_RUNNER_VERSION}.jar --tool org.jmeterplugins.repository.PluginManagerCMD install jpgc-webdriver

Line 16:

![image](https://user-images.githubusercontent.com/57444172/189995328-de9df595-3b3d-446a-ada3-64a1b99266d4.png)

Not sure if i need to add anything more in this file or in the docker file as well.

Please assist and thanks a lot for the awesome videos and repos you have posted so far.
I am yet to view many of those videos and learn from it.

**Comment by QAInsights** [comment]
GitHub's runners are designed for performing headless executions. There are workarounds to running the tests in browser mode. You did install the web driver correctly. Please fork this repo and try again in your repo.
