### ISSUE TITLE
Unable to open jmx file or file doesnt exist

### ISSUE THREAD

**Issue by priyesh-tuli-lab49** [QAInsights/PerfAction#14]
I tried following the whole set-up and executing the test. But I get to see this in the output:

_Execution is being started
**************************
An error occurred: The file /github/workspace/My_test.jmx doesn't exist or can't be opened
**************************
Execution has been completed, please check the artifacts to download the results._

Yoy may take a look at yml:
[https://github.com/priyesh-tuli-lab49/perftest_demo/blob/main/.github/workflows/main.yml](url)

And here are the job stack trace:
[https://github.com/priyesh-tuli-lab49/perftest_demo/actions/runs/3376573932/jobs/5604458636](url)

Could someone please suggest whats wrong with my setup and execution?

**Comment by priyesh-tuli-lab49** [comment]
Resolved. 
yml file required a small updated.

**Comment by dkatzz** [comment]
I'm getting this same issue https://github.com/civiform/civiform/actions/runs/8250989759/job/22566963444. Here is the yaml file: https://github.com/civiform/civiform/blob/dkatz-load-test-fix/.github/workflows/run_jmeter_test.yaml
