### ISSUE TITLE
Getting Error while creating docker image 

### ISSUE THREAD

**Issue by theautomationtesterx** [QAInsights/PerfAction#15]
I have added PerfAction in my workflow to trigger JMeter scripts.
While executing I'm getting the below error.

Step 13/15 : RUN apk --no-cache add curl ca-certificates openjdk9-jre &&     curl -L [https://archive.apache.org/dist/jmeter/binaries/apache-jmeter-${JMETER_VERSION}.tgz](https://archive.apache.org/dist/jmeter/binaries/apache-jmeter-$%7BJMETER_VERSION%7D.tgz) --output /tmp/apache-jmeter-${JMETER_VERSION}.tgz &&     tar -zxvf /tmp/apache-jmeter-${JMETER_VERSION}.tgz &&     mkdir -p /opt/apache &&     mv apache-jmeter-${JMETER_VERSION} /opt/apache &&     rm /tmp/apache-jmeter-${JMETER_VERSION}.tgz &&     rm -rf /var/cache/apk/* &&     chmod a+x /entrypoint.sh &&     chmod a+x /jmeter-plugin-install.sh
   ---> Running in 8c2e89cff7b3
  fetch http://dl-cdn.alpinelinux.org/alpine/v3.11/main/x86_64/APKINDEX.tar.gz
  WARNING: Ignoring http://dl-cdn.alpinelinux.org/alpine/v3.11/main: network error (check Internet connection and firewall)
  fetch http://dl-cdn.alpinelinux.org/alpine/v3.11/community/x86_64/APKINDEX.tar.gz
  WARNING: Ignoring http://dl-cdn.alpinelinux.org/alpine/v3.11/community: network error (check Internet connection and firewall)
  ERROR: unable to select packages:
    ca-certificates (no such package):
      required by: world[ca-certificates]
    curl (no such package):
      required by: world[curl]
    openjdk9-jre (no such package):
      required by: world[openjdk9-jre]
  The command '/bin/sh -c apk --no-cache add curl ca-certificates openjdk9-jre &&     curl -L [https://archive.apache.org/dist/jmeter/binaries/apache-jmeter-${JMETER_VERSION}.tgz](https://archive.apache.org/dist/jmeter/binaries/apache-jmeter-$%7BJMETER_VERSION%7D.tgz) --output /tmp/apache-jmeter-${JMETER_VERSION}.tgz &&     tar -zxvf /tmp/apache-jmeter-${JMETER_VERSION}.tgz &&     mkdir -p /opt/apache &&     mv apache-jmeter-${JMETER_VERSION} /opt/apache &&     rm /tmp/apache-jmeter-${JMETER_VERSION}.tgz &&     rm -rf /var/cache/apk/* &&     chmod a+x /entrypoint.sh &&     chmod a+x /jmeter-plugin-install.sh' returned a non-zero code: 3
Error: Docker build failed with exit code 3

**Comment by QAInsights** [comment]
@theautomationtesterx I smoke tested the action. It is working fine. From your logs, it seems that your repo is not able to reach the internet to download the dependencies. Your corporate firewall or proxy is blocking the access to internet. Please check with your network admins.

I am closing this issue. Thanks!
