### ISSUE TITLE
Empty JTL but without any errors

### ISSUE THREAD

**Issue by fjiang-aamc** [QAInsights/PerfAction#21]
Hi 
I am currently facing an issue on using this action, there is no errors in the log, but the JTL file is empty. I confirm the jmx is correct because It was tested in local by using Jmeter 5.5 via command line. 
![2023-07-24_13-38-14](https://github.com/QAInsights/PerfAction/assets/59448886/7df819c9-54e4-41be-adcd-13ee241fe42c)

**Comment by QAInsights** [comment]
From the console log, it seems that your test did start but not run. Therefore, the JTL is empty. Increase the duration and try again please. Closing this.
