### ISSUE TITLE
Plot Graph of JMETER Run

### ISSUE THREAD

**Issue by pdange** [QAInsights/PerfAction#3]
Hi,

Is there a way to plot graphs from the CSV or JTL file on Github Action using PerfAction?

I am trying to run a jmeter test pipeline, but need to generate graphs at the end from an output jtl or csv file from Jmeter.

Regards,
Palash Dange

**Comment by QAInsights** [comment]
@pdange you can generate HTML report by passing the arguments such -o -e etc. Please refer JMeter documentation for more details. Thanks!

**Comment by pdange** [comment]
Hey @QAInsights , I do know about the Apdex that JMeter generates. May be my questions was not clear. I was wondering if there is a way to get the graphs generated in the report hosted on git action. Something like artifacts in github.
