### ISSUE TITLE
Facing issue for ultimate thread group used

### ISSUE THREAD

**Issue by VW-PriyankaPatil** [QAInsights/PerfAction#4]
Facing this error while running our script
Error in NonGUIDriver java.lang.IllegalArgumentException: Problem loading XML from:'/github/workspace/./test_files/Example.jmx'. 
Cause:
CannotResolveClassException: kg.apc.jmeter.threads.UltimateThreadGroup

 Detail:com.thoughtworks.xstream.converters.ConversionException: 
---- Debugging information ----
cause-exception     : com.thoughtworks.xstream.converters.ConversionException
cause-message       : 
first-jmeter-class  : org.apache.jmeter.save.converters.HashTreeConverter.unmarshal(HashTreeConverter.java:66)
class               : org.apache.jmeter.save.ScriptWrapper
required-type       : org.apache.jmeter.save.ScriptWrapper
converter-type      : org.apache.jmeter.save.ScriptWrapperConverter
path                : /jmeterTestPlan/hashTree/hashTree/kg.apc.jmeter.threads.UltimateThreadGroup
line number         : 199
version             : 5.3
-------------------------------

**Comment by QAInsights** [comment]
Clone this repo and edit https://github.com/QAInsights/PerfAction/blob/master/jmeter-plugin-install.sh to install the Ultimate Thread Group plugin.
