### ISSUE TITLE
Default result file name exist so error on providing new one

### ISSUE THREAD

**Issue by Ajay-056** [QAInsights/PerfAction#5]
Hi Naveen, 

In action.yml file I noted that the result file name is passing as a default name "result.jtl".

This leads to error in the Uploading step stating that the file not found while the user gives a new results file name in the YML File.

I double checked this when giving a new name the non gui command from logs shows still that as "result.jtl"

I have tried like the below but no luck. Could you please check once from your end. Thanks

![Screenshot 2021-10-24 184923](https://user-images.githubusercontent.com/40629789/138596012-0c0cf8ff-d4bb-4c03-98ef-776707937f57.png)

**Comment by QAInsights** [comment]
Please share the job log.

**Comment by Ajay-056** [comment]
Hi Naveen,

Uploaded the Job Log in Zip file. I just now forked the repo and just changed the result file name over there from "result.jtl" to "result-56.jtl". I'm not sure whether what I'm doing is correct If I'm doing something wrong pls correct me this is my fork https://github.com/Ajay-056/PerfAction

[logs_1.zip](https://github.com/QAInsights/PerfAction/files/7448341/logs_1.zip)

![image](https://user-images.githubusercontent.com/40629789/139574217-9e19de9b-6a61-4ca5-b97a-43700d1bdc1f.png

![image](https://user-images.githubusercontent.com/40629789/139574730-eaf83f0a-9471-4e8c-98f0-c5378c5cb528.png)

![image](https://user-images.githubusercontent.com/40629789/139574684-52058326-4cb9-4b7f-8ed3-4ef9715c791b.png)

**Comment by QAInsights** [comment]
@Ajay-056 let me create a new branch and test the arguments.

**Comment by Ajay-056** [comment]
Sure Naveen
