### ISSUE TITLE
Missing HTML Report generation in the artifacts - Enhancement

### ISSUE THREAD

**Issue by Ajay-056** [QAInsights/PerfAction#6]
Hi Naveen,

I have passed the command for generating the HTML Report in the args field but no luck the folder that we are proving has to exist in order to generate the result

I have an idea where we need to get the folder name as input from the user and create that folder before starting the test and then add it to the artifacts so that when the user download will have both JTL and HTML Report

**Comment by QAInsights** [comment]
Have you checked this screenshot https://github.com/QAInsights/PerfAction#download-jmeter-test-results?

**Comment by Ajay-056** [comment]
Yeah Naveen Saw that. I'm trying to add this as an feature / enhancement we can still generate HTML report from JTL file after the action is done in our local machine. But it will be a good automation (with docker) to add the HTML report in the artifacts itself.

**Comment by Ajay-056** [comment]
Hi Naveen,
I have raised a pull request for the above. 
https://github.com/QAInsights/PerfAction/pull/8#issue-1046483389
